name: Deploy UAT to Cloudflare Pages

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Validate Cloudflare configuration
        run: |
          if [ -z "${{ vars.UAT_CLOUDFLARE_PROJECT }}" ]; then
            echo "::error::Repository variable 'UAT_CLOUDFLARE_PROJECT' is not set."
            echo "       Configure it with the Cloudflare Pages project name (e.g. manga-housamkak-uat)."
            exit 1
          fi

      - name: Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.UAT_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.UAT_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.UAT_CLOUDFLARE_PROJECT }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Deployment summary
        run: |
          echo "✅ UAT deployed via Cloudflare Pages"
